version: "3.7"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - wordpress
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      WP_USER_LOWER: ${WP_USER_LOWER}
      WP_PASSWORD_LOWER: ${WP_PASSWORD_LOWER}
      WP_EMAIL_LOWER: ${WP_EMAIL_LOWER}
    expose:
      - 9000
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    networks:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    depends_on:
      - wordpress
    restart: always

networks:
  wordpress:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anajmi/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/anajmi/data/wordpress
